import { StyleSheet } from 'react-native';

export const FaturamentoStyles = StyleSheet.create({
    container:{
      flex: 1,
      backgroundColor: '#EEEEEE',
    },
    Sessao:{
      backgroundColor: '#1A4069',
      borderRadius: 10,
      height: 55,
    },
    nomesessao:{
      fontSize: 18,
      color: '#FFF',
      marginLeft: 20,
      marginTop: 8,
      fontFamily: 'TitilliumWeb',
    },
    variacao:{
      fontSize: 26,
      color: '#032639',
      marginLeft: 0,
      marginTop: 0,
      fontFamily: 'TitilliumWebBold',
    },
    titulocard:{
      fontSize: 18,
      color: '#707070',
      marginTop: -8,
      fontFamily: 'TitilliumWeb',
    },
    subtitulo:{
      fontSize: 13,
      color: '#707070',
      fontFamily: 'TitilliumWeb',
    },
    R$:{
      fontSize: 17,
      color: '#032639',
      marginTop: 4.5,
      marginRight: 3,
      fontFamily: 'TitilliumWebLight',
    },
    valor:{
      fontSize: 21,
      color: '#032639',
      fontFamily: 'TitilliumWebBold',
    },
    grafico2:{
      backgroundColor: '#FFF',
      zIndex: 1,
      marginTop: 5,
      height: 150,
      marginBottom: 0,
      borderRadius: 10,
    },
    grafico:{
      backgroundColor: '#FFF',
      height: 40,
      marginTop: 10,
      marginBottom: 10,
      marginLeft: -10,
      marginRight: -10,
      borderRadius: 10,
    },
    cardTotalizadoresRede:{
      backgroundColor: "#FFF",
      borderRadius: 10,
      height: 'auto',
      marginTop: -15,
      padding: 20,
    },
    cardVariacaoPercentual:{
      backgroundColor: "#FFF",
      borderRadius: 10,
      height: 'auto',
      marginTop: 15,
      padding: 20,
    },
    cardTabelaFaturamento:{
      backgroundColor: "#FFF",
      borderRadius: 10,
      height: 'auto',
      width: 'auto',
      marginTop: 15,
      marginBottom: 15,
      padding: 20,
    },
    cardComprasRede:{
      backgroundColor: "#FFF",
      borderRadius: 10,
      height: 'auto',
      marginTop: 15,
      padding: 20,
      flex: 1,
    },
    cardVendasRede:{
      backgroundColor: "#FFF",
      borderRadius: 10,
      height: 'auto',
      marginTop: 15,
      marginLeft: 15,
      padding: 20,
      flex: 1,
    },
    tabela:{
      marginLeft: -20,
      marginRight: -20,
      height: 'auto',
    },
});